apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: envoy-gateway
  name: envoy-gateway
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: envoy-gateway:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM quay.io/redhattraining/envoy-gateway
      USER 1001
      CMD /usr/local/bin/envoy -c '/opt/app-root/config/envoy.yaml'
    type: Dockerfile
  strategy:
    dockerStrategy:
      env:
        - name: LOGLEVEL
          value: info
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: HGzaU2uqomOXrJDLoCu9
    type: GitHub
  - generic:
      secret: aVttj5olUwUJPlpEPxgX
    type: Generic
  - type: ConfigChange
  - type: ImageChange
