apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    build: shelter-service
  name: shelter-service
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: shelter-service:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: adopt-a-pup/shelter-service
    git:
      uri: https://github.com/jonahkh/DO328-apps
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: J6DU2k5yEa8TF-sVwAzx
    type: GitHub
  - generic:
      secret: j3DkGGG5I7ziGp9ARvau
    type: Generic
  - type: ConfigChange
  - type: ImageChange
