apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-cm
data:
  # change GOSSIP_ENDPOINT to url of the public gossip route,
  # e.g. http://news-gossip.apps-crc.testing
  NEWS_ADDR: GOSSIP_ENDPOINT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
spec:
  selector:
    matchLabels:
      app: exchange
  replicas: 1
  template:
    metadata:
      labels:
        app: exchange
      annotations:
          sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: exchange
          image: quay.io/redhattraining/ossm-exchange:1.0
          ports:
            - containerPort: 8080
          env:
            - name: NEWS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: exchange-cm
                  key: NEWS_ADDR
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange
  name: exchange
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: exchange
