#!/usr/bin/env sh

# Builds webapp production build for v1
# and creates a container image

IMAGE=quay.io/redhattraining/ossm-adopt-a-pup-webapp
APP_VERSION=v1
IMAGE_TAG=1.0

WEBAPP_ROOT=$(cd $(dirname $0)/.. && pwd)
$WEBAPP_ROOT/scripts/build_image $APP_VERSION $IMAGE_TAG
