apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: animal-service
  name: animal-service
spec:
  lookupPolicy:
    local: false
