apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  labels:
    build: adoption-service
  name: adoption-service
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: adoption-service:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: adopt-a-pup/adoption-service
    git:
      uri: https://github.com/jonahkh/DO328-apps
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: Ja9KVdKJiYrjebaALriG
    type: GitHub
  - generic:
      secret: d13Yqaktk7r0Ve-DpWeQ
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/java@sha256:4dc1ae6af9a3efbbd28c1b765faa6fcea3f8eddccd2347ad97713d312f57b511
    type: ImageChange

