
CONTAINER_IMAGE='quay.io/redhattraining/ossm-adopt-a-pup-webapp'

pipeline {
    agent {
        node {
            label 'master'
            customWorkspace 'adopt-a-pup/web-app'
        }
    }

    environment {
        HOME = '${WORKSPACE}'
        NPM_CONFIG_CACHE = '${WORKSPACE}/.npm'
        CI = 'true'
    }

    stages {

        stage('Install') {

            agent {
                docker {
                    image 'node:14'
                    customWorkspace "${workspace}/adopt-a-pup/web-app"
                }
            }

            steps {
                sh 'npm ci'
            }

        }

        stage('Test') {

            agent {
                docker {
                    image 'node:14'
                }
            }

            steps {
                sh 'npm run lint'
                sh 'npm test'
            }

        }

        // stage('NPM build') {

        //     agent {
        //         docker {
        //             image 'node:14'
        //         }
        //     }

        //     steps {
        //         dir('adopt-a-pup/web-app') {
        //             sh 'REACT_APP_VERSION=v1 npm run build'
        //         }
        //         stash includes: 'adopt-a-pup/web-app/build/**/*', name: 'build_v1'

        //         dir('adopt-a-pup/web-app') {
        //             sh 'REACT_APP_VERSION=v2 npm run build'
        //         }
        //         stash includes: 'adopt-a-pup/web-app/build/**/*', name: 'build_v2'
        //     }

        // }

        // stage('Image build & push') {

        //     steps {
        //         sh 'rm -rf build'
        //         unstash 'build_v1'
        //         dir('adopt-a-pup/web-app') {
        //             sh "docker build -t ${CONTAINER_IMAGE} ."
        //             sh "docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:1.0"
        //         }

        //         sh 'rm -rf build'
        //         unstash 'build_v2'
        //         dir('adopt-a-pup/web-app') {
        //             sh "docker build -t ${CONTAINER_IMAGE} ."
        //             sh "docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}:2.0"
        //         }

        //         withDockerRegistry([url: 'https://quay.io/', credentialsId: 'rht_jenkins_quay']) {
        //             sh "docker push ${CONTAINER_IMAGE}"
        //         }

        //     }

        // }

    }
}
