apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-service
spec:
  selector:
    matchLabels:
      app: animal-service
  replicas: 1
  template:
    metadata:
      labels:
        app: animal-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: animal-service
          image: quay.io/psolarvi/ossm-animal-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: animal-service
  name: animal-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: animal-service
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: animal-service-gw
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: animal-service-vs
spec:
  hosts:
    - "*"
  gateways:
    - animal-service-gw
  http:
    - match:
        - uri:
            prefix: /animals
      route:
        - destination:
            host: animal-service
            port:
              number: 8080
