apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
spec:
  selector:
    matchLabels:
      app: email
  replicas: 1
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: maildev/maildev:latest
          imagePullPolicy: Always
          command: ["bin/maildev"]
          args: ["--web", "8080", "--smtp", "1025", "--verbose"]
          ports:
            - containerPort: 1025
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email
  name: email
spec:
  ports:
    - port: 8080
      name: web
      protocol: TCP
      targetPort: 8080
    - port: 25
      name: smtp
      protocol: TCP
      targetPort: 1025
  selector:
    app: email
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: email
  labels:
    app: email
spec:
  to:
    kind: Service
    name: email
  port:
    targetPort: 8080
