apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  selector:
    matchLabels:
      app: frontend-service
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: frontend-service
          image: quay.io/redhattraining/ossm-adopt-a-pup-webapp:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend-service
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-service-gw
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-service-vs
spec:
  hosts:
  - "*"
  gateways:
  - frontend-service-gw
  http:
  - match:
    - uri:
        prefix: /frontend
    rewrite:
      uri: /frontend
    route:
    - destination:
        host: frontend-service
        port:
          number: 3000

