apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  selector:
    matchLabels:
      app: notification
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: notification
          image: quay.io/redhattraining/ossm-notification-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: notification
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: notification
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notification
spec:
  hosts:
    - "*"
  gateways:
    - adoptapup-gateway
  http:
    - match:
        - uri:
            prefix: /notifications
      route:
        - destination:
            host: notification
            port:
              number: 8080
